server:
    port: 8081

spring:
    application:
        name: user-service


    datasource:
        url: ${DATABASE_URL_LOCAL}
        username: ${DATABASE_USERNAME_LOCAL}
        password: ${DATABASE_PASSWORD_LOCAL}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true
        locations: classpath:db/migration
        validate-on-migrate: false
        baseline-on-migrate: true

    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB


jwt:
  secret: ${JWT_SECRET}

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
    url: ${UPLOAD_URL:http://localhost:8081/uploads}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.core.env: TRACE
